Feature/house editor
didevgen/raccoon-city pull request #63
Opened 2020-11-09 18:01 UTC by SalischevAV

Add button 'create section'
Add schema and resolver at back
Add component and mutation at client

2020-11-09 19:07 UTC, letrylesha approved these changes

2020-11-10 14:09 UTC, didevgen commented
You have 2 similar PRs. Please sync them all to avoid future conflicts

2020-11-10 14:09 UTC, didevgen requested changes
See comment above

2020-11-11 16:48 UTC, closed without merging

2020-11-11 16:49 UTC, SalischevAV commented
remote branch is wrong