Fix/remove captcha
didevgen/raccoon-city pull request #65
Opened 2020-11-10 08:42 UTC by SalischevAV

Made comments ad remove verify . If it will be need we can return captcha.

2020-11-10 14:02 UTC, didevgen requested changes

2020-11-10 14:02 UTC, didevgen commented on packages/raccoon-city-graphql/package.json
> +        "build": "set NODE_ENV=production rimraf dist && tsc && yarn copy-to-dist && yarn copyspec",
I have ubuntu on EC2 it will break my builds

2020-11-10 14:02 UTC, didevgen commented on packages/raccoon-city-graphql/src/db/models/apartmentComplex.ts
> +    price: {type: Schema.Types.Number, required: false},
remove

2020-11-10 22:07 UTC, letrylesha approved these changes

2020-11-10 22:07 UTC, letrylesha commented on packages/raccoon-city-graphql/src/resolvers/mutations/house.ts
> +            if (existingSections.length === 0) {
or may be even somethin like this
const maxSectionNumber = !existingSections.length ? 1 : Number(existingSections.length) + 1;

2020-11-10 22:07 UTC, letrylesha commented on packages/raccoon-city-ui/src/components/Main/ChessGrid/FlatSidebarInfo/FlatSidebarModal.tsx
> +                                    // disabled={invalid || !isVerify} //to enable captcha uncomment this string and remove display: none at RecaptchaContainer
rewrite this comment in this format:
// TODO enable captcha uncomment this...

2020-11-10 22:07 UTC, letrylesha commented on packages/raccoon-city-graphql/src/resolvers/mutations/house.ts
> +            console.log('create section error: ', e.message);
remove

2020-11-11 13:03 UTC, closed without merging

2020-11-11 13:03 UTC, SalischevAV commented
all changes moved at previous request