fix carousel colors and height
didevgen/raccoon-city pull request #74
Opened 2020-11-13 17:29 UTC by SalischevAV

fix carousel colors and height

2020-11-17 16:56 UTC, letrylesha approved these changes

2020-11-18 11:23 UTC, didevgen requested changes

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/HouseIcon.tsx
> +
simplify

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/HouseIcons.tsx
> +    height: 15vh;
not sure you want 15vh.
Usually it is used as 100vh or in percents/pixels.

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/HouseIcon.tsx
> +            <div>{partArr.splice(2, partArr.length - 2).join(' ')}</div>
simplify

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/HouseIcon.tsx
> +    }
Use BEM syntax for such cases. e.g `empty` status might be reserved by Mat UI

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/HouseIcon.tsx
>          cursor: pointer;
bad practice to use universal selectors

2020-11-18 11:23 UTC, didevgen commented on packages/raccoon-city-ui/src/components/Main/ApartmentComplexLayout/ApartmentComplexLayout.tsx
> +        .size('100%', '80vh');
don't use vh

2020-11-20 12:24 UTC, merged